
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-11
owner: ucsb-cs156-f24
repo_name: team02-f24-11
pull_requests: [{"author":{"id":"U_kgDOBtZIvw","is_bot":false,"login":"adenjo6","name":"Aden Jo"},"headRefName":"aden-backendfromteam01","number":63,"title":"Added UCSB Organization Backend from team01 into team02","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/63"},{"author":{"id":"MDQ6VXNlcjQzMTU1MjY4","is_bot":false,"login":"smmzhu","name":"Samuel Zhu"},"headRefName":"sam-fixtures","number":62,"title":"created fixture for ucsbdiningcommonsmenuitem","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/62"},{"author":{"id":"MDQ6VXNlcjQzMTU1MjY4","is_bot":false,"login":"smmzhu","name":"Samuel Zhu"},"headRefName":"sam-backend","number":61,"title":"added backend files for ucsbdiningcommonmenuitems","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/61"}]
