title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-f24/team02-f24-11
owner: ucsb-cs156-f24
repo_name: team02-f24-11
pull_requests: [{"author":{"id":"U_kgDOCM7SpA","is_bot":false,"login":"jonathanzhang2027","name":"JonathanZhang"},"headRefName":"LastHelpRequest","number":108,"title":"Last help request","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/108"},{"author":{"id":"U_kgDOCM7SpA","is_bot":false,"login":"jonathanzhang2027","name":"JonathanZhang"},"headRefName":"FinalHelpRequest","number":107,"title":"Final help request","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/107"},{"author":{"id":"U_kgDOCM7SpA","is_bot":false,"login":"jonathanzhang2027","name":"JonathanZhang"},"headRefName":"CreateTableComp","number":104,"title":"Create table comp","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/104"},{"author":{"id":"MDQ6VXNlcjY4MzEyNjY0","is_bot":false,"login":"blobthebuilder","name":"Frank Wang"},"headRefName":"Frank-e2e","number":102,"title":"Frank e2e","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/102"},{"author":{"id":"MDQ6VXNlcjY4MzEyNjY0","is_bot":false,"login":"blobthebuilder","name":"Frank Wang"},"headRefName":"Frank-team03","number":101,"title":"added integration test for article logged in user can get id closes #99","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/101"},{"author":{"id":"U_kgDOCM7SpA","is_bot":false,"login":"jonathanzhang2027","name":"JonathanZhang"},"headRefName":"CreateFormComponent","number":80,"title":"Create form component","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/80"},{"author":{"id":"U_kgDOCM7SpA","is_bot":false,"login":"jonathanzhang2027","name":"JonathanZhang"},"headRefName":"Jonathan-CreateFixtures","number":64,"title":"Copy Files from team01","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/64"}]
