
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-11
owner: ucsb-cs156-f24
repo_name: team02-f24-11
pull_requests: [{"author":{"id":"MDQ6VXNlcjY4MzEyNjY0","is_bot":false,"login":"blobthebuilder","name":"Frank Wang"},"headRefName":"Frank-CreatePage","number":87,"title":"Frank add create page and tests closes #58","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/87"},{"author":{"id":"MDQ6VXNlcjQ2MTEzMzIw","is_bot":false,"login":"JohnLins","name":"John Lins"},"headRefName":"John","number":84,"title":"Menu Item Review Create etc. Pages","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/84"},{"author":{"id":"U_kgDOCM7SpA","is_bot":false,"login":"jonathanzhang2027","name":"JonathanZhang"},"headRefName":"CreateFormComponent","number":80,"title":"Create form component","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/80"},{"author":{"id":"U_kgDOCM7SpA","is_bot":false,"login":"jonathanzhang2027","name":"JonathanZhang"},"headRefName":"Jonathan-CreateFixtures","number":64,"title":"Copy Files from team01","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/64"}]
