
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-11
owner: ucsb-cs156-f24
repo_name: team02-f24-11
pull_requests: [{"author":{"id":"U_kgDOBtZIvw","is_bot":false,"login":"adenjo6","name":"Aden Jo"},"headRefName":"adenIndexPage","number":103,"title":"Index Page for UCSBOrganization plus tests and stories + Edit Page for UCSBOrganization plus tests and stories","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/103"},{"author":{"id":"MDQ6VXNlcjY4MzEyNjY0","is_bot":false,"login":"blobthebuilder","name":"Frank Wang"},"headRefName":"Frank-e2e","number":102,"title":"Frank e2e","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/102"},{"author":{"id":"MDQ6VXNlcjY4MzEyNjY0","is_bot":false,"login":"blobthebuilder","name":"Frank Wang"},"headRefName":"Frank-team03","number":101,"title":"added integration test for article logged in user can get id closes #99","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/101"},{"author":{"id":"MDQ6VXNlcjQ2MTEzMzIw","is_bot":false,"login":"JohnLins","name":"John Lins"},"headRefName":"John","number":84,"title":"Menu Item Review Create etc. Pages","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/84"},{"author":{"id":"U_kgDOCM7SpA","is_bot":false,"login":"jonathanzhang2027","name":"JonathanZhang"},"headRefName":"CreateFormComponent","number":80,"title":"Create form component","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/80"},{"author":{"id":"U_kgDOCM7SpA","is_bot":false,"login":"jonathanzhang2027","name":"JonathanZhang"},"headRefName":"Jonathan-CreateFixtures","number":64,"title":"Copy Files from team01","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/64"}]
