
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-11
owner: ucsb-cs156-f24
repo_name: team02-f24-11
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ2MTEzMzIw","is_bot":false,"login":"JohnLins","name":"John Lins"},"headRefName":"John","number":77,"title":"Add MenuItemReviews frontend parts","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/77"},{"author":{"id":"MDQ6VXNlcjQzMTU1MjY4","is_bot":false,"login":"smmzhu","name":"Samuel Zhu"},"headRefName":"sam-pages","number":75,"title":"finished create, edit, index pages","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/75"},{"author":{"id":"MDQ6VXNlcjY2NDQ1ODIz","is_bot":false,"login":"brianc2730","name":"Brian Cheng"},"headRefName":"Brian-RecommendationRequest-TableComponent","number":74,"title":"Brian - Recommendation Request Table Component","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/74"},{"author":{"id":"MDQ6VXNlcjY4MzEyNjY0","is_bot":false,"login":"blobthebuilder","name":"Frank Wang"},"headRefName":"Frank-Fixtures","number":71,"title":"Frank add fixtures closes #54","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/71"},{"author":{"id":"U_kgDOCM7SpA","is_bot":false,"login":"jonathanzhang2027","name":"JonathanZhang"},"headRefName":"Jonathan-CreateFixtures","number":64,"title":"Copy Files from team01","url":"https://github.com/ucsb-cs156-f24/team02-f24-11/pull/64"}]
